### ISSUE TITLE
Install Dialog and long title names

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2867]
They break the header again. :disappointed:

**Comment by arantius** [comment]
Whoops!  Tried to include the relevant CSS, didn't test.

**Comment by arantius** [comment]
I've just committed (145e125bad5fa51fa2b74670c5946170dc56b6a3) a variety of test scripts.  They're generally useful but also a quick and easy reproduction of this issue.  [Navigate there](https://github.com/greasemonkey/greasemonkey/tree/master/test/scripts) and install either of the long name scripts.  They both act incorrectly.

**Comment by Eselce** [comment]
Ugh, my version numbers are too long for this install dialog! Probably my very own problem... :smile:

**Comment by Sxderp** [comment]
My initial changes that fixed the original issue scaled with both name and version number without problems. I don't see why it wasn't retained. 

Since it looks like the dialog is still having issues (version number length) now.
