### ISSUE TITLE
Unable to install GitHub scripts: "User script download failed"

### ISSUE THREAD

**Issue by fireattack** [greasemonkey/greasemonkey#2896]
Per issue #2631

STR:

1. Install GM 4.3beta7
2. Open https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js
3. Click "raw"
4. Wait the popup times out
5. Click "Install"

GIF:

![heh3](https://user-images.githubusercontent.com/4130991/36950432-79c982ac-1fbb-11e8-89b9-6dcd1ac9c6d4.gif)

**Comment by Sxderp** [comment]
Should be resolved latest master.

**Comment by bluelovers** [comment]
@Sxderp u mean this version?

Version
    4.2
Last updated
    a day ago (Mar 5, 2018)

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/

but this still show download fail

**Comment by fireattack** [comment]
No, he meant the newest version, which for now you can only build it yourself from the source code.

Or you can wait until they update at least beta8 here: https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta

**Comment by arantius** [comment]
Confirmed working on latest nightly.  Release pending.

**Comment by mescalero01** [comment]
Hello everybody,
  same here:
Greasmonkey installed for firefox (last version 59.0.2:
tryied to install the userscript from different sources:
greasyfork.org
openuserjs.org
github.com
reeksite.com

Result is always the same:

![userscript_failed](https://user-images.githubusercontent.com/38278093/38604268-1d49ce38-3d70-11e8-943f-578b8baf375d.png)

Any idea?

Regards.
