### ISSUE TITLE
'Greasemonkey Wiki' menu option has broken link

### ISSUE THREAD

**Issue by ludovic-tc** [greasemonkey/greasemonkey#3155]
Version **4.11**:

The 'Greasemonkey Wiki' menu option in the menu that appears when you click on the monkey's head icon in the Extensions Toolbar has a broken link, viz.:

http://wiki2.greasespot.net/Main_Page

This is a broken link which causes a 'Server Not Found' error. It is also uses simple HTTP protocol which is undesirable. The correct link to the wiki is of course:

https://wiki.greasespot.net/Main_Page

**Comment by arantius** [comment]
Thank you for the report.  A mistake was made in a recent server/software upgrade.  The site should be working again.  (And, yes, encrypted.)

**Comment by ludovic-tc** [comment]
I am still getting “server not found” when I visit http://wiki2.greasespot.net/Main_Page .

**Comment by arantius** [comment]
That's an incorrect URL (it was only intended for testing).  Use the menu or manually remove the "2" .

https://wiki.greasespot.net/Main_Page
